title : pmarques
tagline:
author :
  name : Paulo Marques
  email : pjp.marques@gmail.com
  github : pjpmarques
#  twitter : username
#  feedburner : feedname

navigation :
#  - archive.md
  - publications.md
#  - about.md
