title : pmarques
tagline:
author :
  name : Paulo Marques
  email : pjp.marques@gmail.com
  github : pjpmarques
#  twitter : username
#  feedburner : feedname

navigation :
#  - archive.md
  - publications.md
  - <a href="https://github.com/pjpmarques/">GitHub</a>
  - language.md
  - about.md
