title : pmarques
tagline:
author :
  name : Paulo Marques
  email : pjp.marques@gmail.com
  github : pjpmarques
#  twitter : username
#  feedburner : feedname

navigation :
#  - archive.md
  - publications.md
  - [GitHub](https://github.com/pjpmarques/)
  - language.md
  - about.md
